INSERT INTO FEEDBACK (PRODUCTNUMBER, GARMENTTYPE, AGEOFGARMENT, LEVELOFUSE, COLOR, SEAM, PRINT, SHRINKAGE, DURABILITY, MATERIAL, COMMENT, DATESUBMITTED)
VALUES (123, 'Skirt', 3, 5, 1, 5, 5, 3, 3, 2, 'Great', '2021-08-23');
INSERT INTO FEEDBACK (PRODUCTNUMBER, GARMENTTYPE, AGEOFGARMENT, LEVELOFUSE, COLOR, SEAM, PRINT, SHRINKAGE, DURABILITY, MATERIAL, COMMENT, DATESUBMITTED)
VALUES (123, 'Shirt', 3, 5, 1, 5, 5, 3, 3, 2, 'Bad', '2021-08-22');