CREATE TABLE FEEDBACK(
  PRODUCTNUMBER VARCHAR(10) NOT NULL,
  GARMENTTYPE VARCHAR(20) NOT NULL,
  AGEOFGARMENT INTEGER NOT NULL,
  LEVELOFUSE INTEGER NOT NULL,
  COLOR INTEGER NOT NULL,
  SEAM INTEGER NOT NULL,
  PRINT INTEGER NOT NULL,
  SHRINKAGE INTEGER NOT NULL,
  MATERIAL INTEGER NOT NULL,
  COMMENT VARCHAR(256),
  DATESUBMITTED VARCHAR(20),
  ID BIGINT AUTO_INCREMENT PRIMARY KEY
);